export const turkish_alphabets = [
  { id: 1, capital: "A", small: "a", sound: "ah", example: "araba", exampleTranslation: "car" },
  { id: 2, capital: "B", small: "b", sound: "beh", example: "balık", exampleTranslation: "fish" },
  { id: 3, capital: "C", small: "c", sound: "jeh", example: "cam", exampleTranslation: "glass" },
  { id: 4, capital: "Ç", small: "ç", sound: "cheh", example: "çay", exampleTranslation: "tea" },
  { id: 5, capital: "D", small: "d", sound: "deh", example: "deniz", exampleTranslation: "sea" },
  { id: 6, capital: "E", small: "e", sound: "eh", example: "ev", exampleTranslation: "house" },
  { id: 7, capital: "F", small: "f", sound: "feh", example: "fil", exampleTranslation: "elephant" },
  { id: 8, capital: "G", small: "g", sound: "geh", example: "gül", exampleTranslation: "rose" },
  { id: 9, capital: "Ğ", small: "ğ", sound: "soft g", example: "dağ", exampleTranslation: "mountain" },
  { id: 10, capital: "H", small: "h", sound: "heh", example: "hayat", exampleTranslation: "life" },
  { id: 11, capital: "I", small: "ı", sound: "uh", example: "ırmak", exampleTranslation: "river" },
  { id: 12, capital: "İ", small: "i", sound: "ee", example: "ilim", exampleTranslation: "science" },
  { id: 13, capital: "J", small: "j", sound: "zheh", example: "jilet", exampleTranslation: "razor" },
  { id: 14, capital: "K", small: "k", sound: "keh", example: "kitap", exampleTranslation: "book" },
  { id: 15, capital: "L", small: "l", sound: "leh", example: "limon", exampleTranslation: "lemon" },
  { id: 16, capital: "M", small: "m", sound: "meh", example: "masa", exampleTranslation: "table" },
  { id: 17, capital: "N", small: "n", sound: "neh", example: "nehir", exampleTranslation: "river" },
  { id: 18, capital: "O", small: "o", sound: "oh", example: "okul", exampleTranslation: "school" },
  { id: 19, capital: "Ö", small: "ö", sound: "eu", example: "ördek", exampleTranslation: "duck" },
  { id: 20, capital: "P", small: "p", sound: "peh", example: "pencere", exampleTranslation: "window" },
  { id: 21, capital: "R", small: "r", sound: "reh", example: "rüya", exampleTranslation: "dream" },
  { id: 22, capital: "S", small: "s", sound: "seh", example: "salata", exampleTranslation: "salad" },
  { id: 23, capital: "Ş", small: "ş", sound: "sheh", example: "şemsiye", exampleTranslation: "umbrella" },
  { id: 24, capital: "T", small: "t", sound: "teh", example: "tarla", exampleTranslation: "field" },
  { id: 25, capital: "U", small: "u", sound: "oo", example: "uçak", exampleTranslation: "airplane" },
  { id: 26, capital: "Ü", small: "ü", sound: "eu", example: "üzüm", exampleTranslation: "grape" },
  { id: 27, capital: "V", small: "v", sound: "veh", example: "vazo", exampleTranslation: "vase" },
  { id: 28, capital: "Y", small: "y", sound: "yeh", example: "yaprak", exampleTranslation: "leaf" },
  { id: 29, capital: "Z", small: "z", sound: "zeh", example: "zebra", exampleTranslation: "zebra" }
] as const;
